[env:giga_r1_wifi]
platform = ststm32
board = giga_r1_m7
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbmodem1101
monitor_port = /dev/cu.usbmodem1101
lib_deps =
  https://github.com/HuskyLens/HUSKYLENSArduino/archive/refs/heads/master.zip
  https://github.com/arduino-libraries/Servo/archive/refs/heads/master.zip
